language: generic
sudo: false

os:
  - linux
  - osx

install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export OS=MacOSX; else export OS=Linux; fi
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-$OS-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - hash -r
  - source $HOME/miniconda/etc/profile.d/conda.sh
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  - conda install conda-build anaconda-client
  - conda build conda -c defaults -c conda-forge -c bioconda
  - conda build conda -c defaults -c conda-forge -c bioconda | tee .packages

deploy:
  - provider: script
    script: conda/deploy.sh
    on:
      repo: popgenmethods/momi
      tags: true
    skip_cleanup: true
