matrix:
  include:
    - os: linux
      # only used for uploading to pypi
      language: python
      python: 3.6
    - os: osx
      language: generic

install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export OS=MacOSX; else export OS=Linux; fi
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-$OS-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - hash -r
  - source $HOME/miniconda/etc/profile.d/conda.sh
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  - conda install conda-build anaconda-client

script:
  - conda build conda -c defaults -c conda-forge -c bioconda
  - conda build conda -c defaults -c conda-forge -c bioconda --output | tee .packages

deploy:
  - provider: script
    script: conda/deploy.sh
    on:
      repo: popgenmethods/momi2
      tags: true
    skip_cleanup: true
  - provider: pypi
    user: "jackkamm"
    password:
      secure: "kerxFuTfwFJGYKQjHzG37whXtorobrcK8B6XfzRUc5yeVSc7i5VkjSLDWNjcEDUtj7BXdo5RwulvefNyPG53cLbOAlToW3fZuhDFuWxi2wyrsyWTkUcRQ8oaBBqDGtu8xiwfgOIqXYs0Kd4vAiT1xNLYuRU0JqLI0jrMd277ef71DJGQWggrpz6WUlh/U8l9aOdCbDHkjO7WfblU68JJfCEP1N3RrsFGttVsvtHAn33Q+FxcW+8GqV8FHhqpGipz/kMcKQ/l/gOymKUi1L5kuuGXAJPeIkSec2P+AAFxqTKYNe8fYHefPtKcSF1XtiHEwt1jRAuEVsBJhCjdcfbxX0uSgzqAzcDi03X06BgkvSJ7afPW++8HQRyil7ar0WQEK/31q13Tb9BbeypWnCJ9IyZCcz6iSESS878ChA7qOvnZccHHx/ZWGiFbRV5gQGyapNPiMi2Y+xhUwmxDwZH3U+MBcCuxFtqKcezJCfJjXZvt3zdQer11SXXncnHyCcWKf9vutSpaX5qtSVVD1xeBrEBYkKpTO8kF5YXaDfMD5le/8Ud8U6Urgp8SxK+eTpx3ajSc3zXzp9nHfCyLw10vHGuUGVviln4hwTUsJAXZ09A2sX+H6AvOIYXHDE4rTzdP9tLVuyTz3qTAhw1W2YLFPY8ciRgsMmrQcB4pDlD6T6I="
    on:
      condition: $TRAVIS_OS_NAME = linux
      repo: popgenmethods/momi2
      tags: true
    skip_cleanup: true
