matrix:
  include:
    - os: linux
      # only used for uploading to pypi
      language: python
      python: 3.6
    - os: osx
      language: generic

install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export OS=MacOSX; else export OS=Linux; fi
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-$OS-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - hash -r
  - source $HOME/miniconda/etc/profile.d/conda.sh
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  - conda install conda-build anaconda-client

script:
  - conda build conda -c defaults -c conda-forge -c bioconda
  - conda build conda -c defaults -c conda-forge -c bioconda --output | tee .packages

deploy:
  - provider: script
    script: conda/deploy.sh
    on:
      repo: popgenmethods/momi2
      tags: true
    skip_cleanup: true
  - provider: pypi
    user: "jackkamm"
    password:
      secure: "WjzDRqhKV2ycU8OKTtfQWcdbnYmgtnqcBCJ5CPCZO5sBHIm9h+GnySs5jRz1Y4gEv09gG6KLvwsDT9IEOtcJA25a/99xOXKkQpo80yQLDWXAIElEaws1B09UMbzKnZtRMLca8QiSlyjtv3DxulBYQSAimI8fQUOX++f1G6QBu4W48yNPmZ8ogEsrBkKgNzhtDUgA1vHTI2H0WFXbj3AQLLEdjpDvhhNO/ce5J+60hcV2gv8U+jarxT9kB4DHcG8lNhIvPevzEFS9sj8u+9dXse5MzKU2pwNLd5vWdcDzpYHxvZsODrdKO9Sa92+OrbSOOt7G19iY2yLsKEFiBc/Zszs9+8ZYErg3JAmmF5uJGGc4vgIE9fcI5bwAjMf8OF75qxJdwJyQAzAO1qHchyAuM+Po2UsiBwdjb2E5fdQ37fvbh3m6EhbDm0Gvw0EzTEKZ2OU/556ZmnaNO3yJcA5W1MpBFzzudvTv1Dyo3YHoBBaqcwNKIfLuE3AoUp1PFwQD4oAtOgydDlGKXkdfa4l7UQqj8xo1OWq0IAjr8rl8NtsNNi6ImjdTXMJfKApZV/dkYOySs50/GKXCxp2ktNmId2Rp3LfXW0ZMWM6CW75bCLrF2najTUS/6gD2X+5IIzJQpPRE4tfMh7PWiBk72rG6TE9NBYTVpLdsmt+p8rjBDRg="
    on:
      os: linux
      repo: popgenmethods/momi2
      tags: true
    skip_cleanup: true
