{% set name = "pysam" %}
{% set version = "0.14.1" %}
{% set file_ext = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash_value = "2e86f5228429d08975c8adb9030296699012a8deba8ba26cbfc09b374f792c97" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.{{ file_ext }}'
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ file_ext }}
  '{{ hash_type }}': '{{ hash_value }}'

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  host:
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - pysam
    - pysam.include
    - pysam.include.bcftools
    - pysam.include.htslib
    - pysam.include.htslib.htslib
    - pysam.include.samtools
    - pysam.include.samtools.win32

about:
  home: https://github.com/pysam-developers/pysam
  license: MIT
  license_family: MIT
  license_file: ''
  summary: pysam
  description: 'pysam - a python module for reading, manipulating and writing

    genomic data sets.


    pysam is a lightweight wrapper of the htslib C-API and provides

    facilities to read and write SAM/BAM/VCF/BCF/BED/GFF/GTF/FASTA/FASTQ

    files as well as access to the command line functionality of the

    samtools and bcftools packages. The module supports compression and

    random access through indexing.


    This module provides a low-level wrapper around the htslib C-API as

    using cython and a high-level API for convenient access to the data

    within standard genomic file formats.


    The current version wraps htslib-1.7, samtools-1.7 and bcftools-1.6.


    See:

    http://www.htslib.org

    https://github.com/pysam-developers/pysam

    http://pysam.readthedocs.org/en/stable


    '
  doc_url: ''
  dev_url: ''

extra:
  recipe-maintainers: ''
